### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LukeZBaker** [keshavbhatt/lyricpad#1]
Is LyricPad published under the MIT License?

**Comment by keshavbhatt** [comment]
App and its code is published under [WTFPL](https://en.m.wikipedia.org/wiki/WTFPL?wprov=sfla1) license.

**Comment by LukeZBaker** [comment]
Thanks! I'm writing a review of this software. Recently published a review of another one of your apps (olivia).

**Comment by keshavbhatt** [comment]
thanks :) 😘
